[package]
name = "rocket-include-handlebars"
version = "0.5.0"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/rocket-include-handlebars"
homepage = "https://magiclen.org/rocket-include-handlebars"
keywords = ["rocket", "server", "web", "static", "handlebars"]
categories = ["parsing"]
description= "This is a crate which provides macros `handlebars_resources_initialize!` and `handlebars_response!` to statically include HBS (Handlebars) files from your Rust project and make them be the HTTP response sources quickly."
readme = "README.md"
license = "MIT"

[dependencies]
rocket = "0.3.15"
lazy_static = "1.1.0"
lazy-static-include = "1.1"
crc-any = "1.0.0"
handlebars = "1.0.1"
rocket-etag-if-none-match = "0.1.0"
html-minifier = "1.1.2"
json-gettext = "1.5.2"

[dev-dependencies]
rocket_codegen = "0.3.15"