[package]
name = "rocket-include-handlebars"
version = "0.8.1"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/rocket-include-handlebars"
homepage = "https://magiclen.org/rocket-include-handlebars"
keywords = ["rocket", "server", "web", "static", "handlebars"]
categories = ["web-programming"]
description= "This is a crate which provides macros `handlebars_resources_initialize!` and `handlebars_response!` to statically include HBS (Handlebars) files from your Rust project and make them be the HTTP response sources quickly."
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/rocket-include-handlebars", branch = "master" }

[dependencies]
rocket = "0.4"
crc-any = "1.0.0"
handlebars = "1.1.0"
html-minifier = "1.1.3"

rocket-etag-if-none-match = "0.3"

[dev-dependencies]
lazy_static = "1.1.0"
lazy-static-include = "1.2"

json-gettext = "2.1.0"